apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: sidartasilva/gitopsfullcycle
  newTag: c798203be8c37d7530c3a1d99fa4e9049c8b054b
